/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GalleriesRouteImport } from './routes/galleries'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiCatalogIntegrityRouteImport } from './routes/api/catalog-integrity'
import { Route as ApiCommerceRouteImport } from './routes/api/commerce'
import { Route as ApiCommerceDownloadRouteImport } from './routes/api/commerce-download'
import { Route as ApiCommerceWebhookRouteImport } from './routes/api/commerce-webhook'
import { Route as ApiSportsRouteImport } from './routes/api/sports'
import { Route as CheckoutThanksRouteImport } from './routes/checkout.thanks'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'
import { Route as GalleriesIndexRouteImport } from './routes/galleries.index'
import { Route as GalleriesGalleryIdRouteImport } from './routes/galleries.$galleryId'
import { Route as KeywordsIndexRouteImport } from './routes/keywords.index'
import { Route as KeywordsTagRouteImport } from './routes/keywords.$tag'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCatalogSplatRouteImport } from './routes/api/catalog_.$'
import { Route as ApiSmugmugCallbackRouteImport } from './routes/api/smugmug.callback'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks.stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesRoute = GalleriesRouteImport.update({
  id: '/galleries',
  path: '/galleries',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogIntegrityRoute = ApiCatalogIntegrityRouteImport.update({
  id: '/api/catalog-integrity',
  path: '/api/catalog-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommerceRoute = ApiCommerceRouteImport.update({
  id: '/api/commerce',
  path: '/api/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommerceDownloadRoute = ApiCommerceDownloadRouteImport.update({
  id: '/api/commerce-download',
  path: '/api/commerce-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommerceWebhookRoute = ApiCommerceWebhookRouteImport.update({
  id: '/api/commerce-webhook',
  path: '/api/commerce-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSportsRoute = ApiSportsRouteImport.update({
  id: '/api/sports',
  path: '/api/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutThanksRoute = CheckoutThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => CheckoutRoute,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIndexRoute = GalleriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleriesRoute,
} as any)
const GalleriesGalleryIdRoute = GalleriesGalleryIdRouteImport.update({
  id: '/$galleryId',
  path: '/$galleryId',
  getParentRoute: () => GalleriesRoute,
} as any)
const KeywordsIndexRoute = KeywordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeywordsRoute,
} as any)
const KeywordsTagRoute = KeywordsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => KeywordsRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogSplatRoute = ApiCatalogSplatRouteImport.update({
  id: '/api/catalog_/$',
  path: '/api/catalog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmugmugCallbackRoute = ApiSmugmugCallbackRouteImport.update({
  id: '/api/smugmug/callback',
  path: '/api/smugmug/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/commerce': typeof CommerceRoute
  '/favorites': typeof FavoritesRoute
  '/galleries': typeof GalleriesRouteWithChildren
  '/keywords': typeof KeywordsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/migrate': typeof MigrateRoute
  '/organize': typeof OrganizeRoute
  '/publish': typeof PublishRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/catalog-integrity': typeof ApiCatalogIntegrityRoute
  '/api/commerce': typeof ApiCommerceRoute
  '/api/commerce-download': typeof ApiCommerceDownloadRoute
  '/api/commerce-webhook': typeof ApiCommerceWebhookRoute
  '/api/sports': typeof ApiSportsRoute
  '/checkout/thanks': typeof CheckoutThanksRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/galleries/$galleryId': typeof GalleriesGalleryIdRoute
  '/keywords/$tag': typeof KeywordsTagRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/galleries/': typeof GalleriesIndexRoute
  '/keywords/': typeof KeywordsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/$': typeof ApiCatalogSplatRoute
  '/api/smugmug/callback': typeof ApiSmugmugCallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/commerce': typeof CommerceRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/migrate': typeof MigrateRoute
  '/organize': typeof OrganizeRoute
  '/publish': typeof PublishRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/catalog-integrity': typeof ApiCatalogIntegrityRoute
  '/api/commerce': typeof ApiCommerceRoute
  '/api/commerce-download': typeof ApiCommerceDownloadRoute
  '/api/commerce-webhook': typeof ApiCommerceWebhookRoute
  '/api/sports': typeof ApiSportsRoute
  '/checkout/thanks': typeof CheckoutThanksRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/galleries/$galleryId': typeof GalleriesGalleryIdRoute
  '/keywords/$tag': typeof KeywordsTagRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/galleries': typeof GalleriesIndexRoute
  '/keywords': typeof KeywordsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/$': typeof ApiCatalogSplatRoute
  '/api/smugmug/callback': typeof ApiSmugmugCallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/commerce': typeof CommerceRoute
  '/favorites': typeof FavoritesRoute
  '/galleries': typeof GalleriesRouteWithChildren
  '/keywords': typeof KeywordsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/migrate': typeof MigrateRoute
  '/organize': typeof OrganizeRoute
  '/publish': typeof PublishRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/catalog-integrity': typeof ApiCatalogIntegrityRoute
  '/api/commerce': typeof ApiCommerceRoute
  '/api/commerce-download': typeof ApiCommerceDownloadRoute
  '/api/commerce-webhook': typeof ApiCommerceWebhookRoute
  '/api/sports': typeof ApiSportsRoute
  '/checkout/thanks': typeof CheckoutThanksRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/galleries/$galleryId': typeof GalleriesGalleryIdRoute
  '/keywords/$tag': typeof KeywordsTagRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/galleries/': typeof GalleriesIndexRoute
  '/keywords/': typeof KeywordsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog_/$': typeof ApiCatalogSplatRoute
  '/api/smugmug/callback': typeof ApiSmugmugCallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/commerce'
    | '/favorites'
    | '/galleries'
    | '/keywords'
    | '/library'
    | '/login'
    | '/migrate'
    | '/organize'
    | '/publish'
    | '/sell'
    | '/settings'
    | '/upload'
    | '/api/catalog'
    | '/api/catalog-integrity'
    | '/api/commerce'
    | '/api/commerce-download'
    | '/api/commerce-webhook'
    | '/api/sports'
    | '/checkout/thanks'
    | '/folders/$folderId'
    | '/galleries/$galleryId'
    | '/keywords/$tag'
    | '/orders/$orderId'
    | '/galleries/'
    | '/keywords/'
    | '/api/auth/$'
    | '/api/catalog/$'
    | '/api/smugmug/callback'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/commerce'
    | '/favorites'
    | '/library'
    | '/login'
    | '/migrate'
    | '/organize'
    | '/publish'
    | '/sell'
    | '/settings'
    | '/upload'
    | '/api/catalog'
    | '/api/catalog-integrity'
    | '/api/commerce'
    | '/api/commerce-download'
    | '/api/commerce-webhook'
    | '/api/sports'
    | '/checkout/thanks'
    | '/folders/$folderId'
    | '/galleries/$galleryId'
    | '/keywords/$tag'
    | '/orders/$orderId'
    | '/galleries'
    | '/keywords'
    | '/api/auth/$'
    | '/api/catalog/$'
    | '/api/smugmug/callback'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/commerce'
    | '/favorites'
    | '/galleries'
    | '/keywords'
    | '/library'
    | '/login'
    | '/migrate'
    | '/organize'
    | '/publish'
    | '/sell'
    | '/settings'
    | '/upload'
    | '/api/catalog'
    | '/api/catalog-integrity'
    | '/api/commerce'
    | '/api/commerce-download'
    | '/api/commerce-webhook'
    | '/api/sports'
    | '/checkout/thanks'
    | '/folders/$folderId'
    | '/galleries/$galleryId'
    | '/keywords/$tag'
    | '/orders/$orderId'
    | '/galleries/'
    | '/keywords/'
    | '/api/auth/$'
    | '/api/catalog_/$'
    | '/api/smugmug/callback'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CommerceRoute: typeof CommerceRoute
  FavoritesRoute: typeof FavoritesRoute
  GalleriesRoute: typeof GalleriesRouteWithChildren
  KeywordsRoute: typeof KeywordsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MigrateRoute: typeof MigrateRoute
  OrganizeRoute: typeof OrganizeRoute
  PublishRoute: typeof PublishRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiCatalogIntegrityRoute: typeof ApiCatalogIntegrityRoute
  ApiCommerceRoute: typeof ApiCommerceRoute
  ApiCommerceDownloadRoute: typeof ApiCommerceDownloadRoute
  ApiCommerceWebhookRoute: typeof ApiCommerceWebhookRoute
  ApiSportsRoute: typeof ApiSportsRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCatalogSplatRoute: typeof ApiCatalogSplatRoute
  ApiSmugmugCallbackRoute: typeof ApiSmugmugCallbackRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries': {
      id: '/galleries'
      path: '/galleries'
      fullPath: '/galleries'
      preLoaderRoute: typeof GalleriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog-integrity': {
      id: '/api/catalog-integrity'
      path: '/api/catalog-integrity'
      fullPath: '/api/catalog-integrity'
      preLoaderRoute: typeof ApiCatalogIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commerce': {
      id: '/api/commerce'
      path: '/api/commerce'
      fullPath: '/api/commerce'
      preLoaderRoute: typeof ApiCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commerce-download': {
      id: '/api/commerce-download'
      path: '/api/commerce-download'
      fullPath: '/api/commerce-download'
      preLoaderRoute: typeof ApiCommerceDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commerce-webhook': {
      id: '/api/commerce-webhook'
      path: '/api/commerce-webhook'
      fullPath: '/api/commerce-webhook'
      preLoaderRoute: typeof ApiCommerceWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sports': {
      id: '/api/sports'
      path: '/api/sports'
      fullPath: '/api/sports'
      preLoaderRoute: typeof ApiSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/thanks': {
      id: '/checkout/thanks'
      path: '/thanks'
      fullPath: '/checkout/thanks'
      preLoaderRoute: typeof CheckoutThanksRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/': {
      id: '/galleries/'
      path: '/'
      fullPath: '/galleries/'
      preLoaderRoute: typeof GalleriesIndexRouteImport
      parentRoute: typeof GalleriesRoute
    }
    '/galleries/$galleryId': {
      id: '/galleries/$galleryId'
      path: '/$galleryId'
      fullPath: '/galleries/$galleryId'
      preLoaderRoute: typeof GalleriesGalleryIdRouteImport
      parentRoute: typeof GalleriesRoute
    }
    '/keywords/': {
      id: '/keywords/'
      path: '/'
      fullPath: '/keywords/'
      preLoaderRoute: typeof KeywordsIndexRouteImport
      parentRoute: typeof KeywordsRoute
    }
    '/keywords/$tag': {
      id: '/keywords/$tag'
      path: '/$tag'
      fullPath: '/keywords/$tag'
      preLoaderRoute: typeof KeywordsTagRouteImport
      parentRoute: typeof KeywordsRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog_/$': {
      id: '/api/catalog_/$'
      path: '/api/catalog/$'
      fullPath: '/api/catalog/$'
      preLoaderRoute: typeof ApiCatalogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smugmug/callback': {
      id: '/api/smugmug/callback'
      path: '/api/smugmug/callback'
      fullPath: '/api/smugmug/callback'
      preLoaderRoute: typeof ApiSmugmugCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutThanksRoute: typeof CheckoutThanksRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutThanksRoute: CheckoutThanksRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface GalleriesRouteChildren {
  GalleriesGalleryIdRoute: typeof GalleriesGalleryIdRoute
  GalleriesIndexRoute: typeof GalleriesIndexRoute
}

const GalleriesRouteChildren: GalleriesRouteChildren = {
  GalleriesGalleryIdRoute: GalleriesGalleryIdRoute,
  GalleriesIndexRoute: GalleriesIndexRoute,
}

const GalleriesRouteWithChildren = GalleriesRoute._addFileChildren(
  GalleriesRouteChildren,
)

interface KeywordsRouteChildren {
  KeywordsTagRoute: typeof KeywordsTagRoute
  KeywordsIndexRoute: typeof KeywordsIndexRoute
}

const KeywordsRouteChildren: KeywordsRouteChildren = {
  KeywordsTagRoute: KeywordsTagRoute,
  KeywordsIndexRoute: KeywordsIndexRoute,
}

const KeywordsRouteWithChildren = KeywordsRoute._addFileChildren(
  KeywordsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CommerceRoute: CommerceRoute,
  FavoritesRoute: FavoritesRoute,
  GalleriesRoute: GalleriesRouteWithChildren,
  KeywordsRoute: KeywordsRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MigrateRoute: MigrateRoute,
  OrganizeRoute: OrganizeRoute,
  PublishRoute: PublishRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiCatalogIntegrityRoute: ApiCatalogIntegrityRoute,
  ApiCommerceRoute: ApiCommerceRoute,
  ApiCommerceDownloadRoute: ApiCommerceDownloadRoute,
  ApiCommerceWebhookRoute: ApiCommerceWebhookRoute,
  ApiSportsRoute: ApiSportsRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCatalogSplatRoute: ApiCatalogSplatRoute,
  ApiSmugmugCallbackRoute: ApiSmugmugCallbackRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
